---
# Be sure to call this with --extra-vars="hosts=<hostname>"
- hosts: "{{ hosts }}"
  gather_facts: False 
  sudo: yes
  vars:
    - app_home: "/var/www/weekend-plans"
    - git_repo: "https://github.com/edthedev/weekend-plans.git"
    # Debian: - httpd_conf: /etc/apache2/apache2.conf
    - httpd_conf: /etc/httpd/conf/httpd.conf
    - pip_download: https://bootstrap.pypa.io/get-pip.py
  tasks:
    - yum:
        name="{{ item }}"
        state=installed
      with_items:
        - git-core
        - python
        - mod_wsgi
    - name: install pip
      shell: "curl {{ pip_download }} | python -"
      args:
        creates: "/usr/bin/pip"
    - git: 
        dest="{{ app_home }}" 
        repo="{{ git_repo }}"
        update=yes
        force=yes
        depth=1
        version=HEAD
      tags: fixed
      notify: restart_apache
    - django_manage:
        app_path="{{ app_home }}"
        command=migrate
      tags: fixed
    - pip: requirements="{{ app_home }}/requirements.txt"
    - name: set wsgi.py
      lineinfile: 
        dest="{{ httpd_conf }}"
        state=present
        line="WSGIScriptAlias / {{ app_home }}/main/wsgi.py"
      notify: restart_apache
    - name: set python path
      lineinfile: 
        dest="{{ httpd_conf }}"
        state=present
        line="WSGIPythonPath {{ app_home }}"
      notify: restart_apache
    - name: app readable by apache
      file: 
        path="{{ app_home }}"
        group=apache
        recurse=yes
        mode=776
  handlers:
    - name: restart_apache
      shell: sudo /sbin/service httpd stop; sleep 2; sudo /sbin/service httpd start
