---
# Be sure to call this with --extra-vars="hosts=<hostname>"
- hosts: "{{ hosts }}"
  gather_facts: False 
  sudo: yes
  vars:
    - app_home: "/var/www/weekend-plans"
    - git_repo: "https://github.com/edthedev/weekend-plans.git"
    # Debian: - httpd_conf: /etc/apache2/apache2.conf
    - httpd_conf: /etc/httpd/conf/httpd.conf
    - pip_download: https://bootstrap.pypa.io/get-pip.py
  tasks:
    # The basic required software.
    # - yum:
    #    name="{{ item }}"
    #    state=installed
    #  with_items:
    #    - git-core
    #    - python
    #    - mod_wsgi
    - apt:
        name="{{ item }}"
        state=installed
      with_items:
        - apache2
        - git
        - libapache2-mod-wsgi
        - python-pip
    # Specific libraries for this application.
    - name: install pip
      shell: "curl {{ pip_download }} | python -"
      args:
        creates: "/usr/bin/pip"
    # The application, itself.
    - git: 
        dest="{{ app_home }}" 
        repo="{{ git_repo }}"
        update=yes
        force=yes
        depth=1
        version=cosmetic
      tags: fixed
      notify: restart_apache
    # The application database.
    - pip: requirements="{{ app_home }}/requirements.txt"
    - django_manage:
        app_path="{{ app_home }}"
        command=syncdb
    # The webserver configuration.
    - name: set wsgi.py
      lineinfile: 
        dest="{{ httpd_conf }}"
        state=present
        line="WSGIScriptAlias / {{ app_home }}/main/wsgi.py"
      notify: restart_apache
    - name: setup apache static files
      lineinfile: 
        dest="{{ httpd_conf }}"
        state=present
        line="Alias /static {{ app_home }}/static"
      notify: restart_apache
    - name: set python path
      lineinfile: 
        dest="{{ httpd_conf }}"
        state=present
        line="WSGIPythonPath {{ app_home }}"
      notify: restart_apache
    - name: app readable by apache
      file: 
        path="{{ app_home }}"
        group=apache
        recurse=yes
        mode=776
    - file:
        state=link
        src=/usr/share/zoneinfo/America/Chicago
        dest=/etc/localtime
        force=yes
  handlers:
    - name: restart_apache
      shell: sudo /sbin/service httpd stop; sleep 2; sudo /sbin/service httpd start
