---
# Be sure to call this with --extra-vars="hosts=<hostname>"
- hosts: "{{ hosts }}"
  gather_facts: False 
  sudo: yes
  vars:
    - temp_dir: /tmp
    - py_dir: "{{ temp_dir }}/Python-2.7.6"
    - python_tar: Python-2.7.6.tgz
  tasks:
    - yum:
        name="{{ item }}"
        state=installed
      with_items:
        - zlib-devel
        - bzip2-devel
        - openssl-devel
        - ncurses-devel
    #- unarchive:
    #    src="{{ python_tar }}"
    #    dest="{{ temp_dir }}"
    #    creates="/tmp/Python-2.7.6/configure"
    - shell: "cd {{ py_dir }}; ./configure"
    - shell: "cd {{ py_dir }}; make"
    - shell: "cd {{ py_dir }}; make altinstall"
    - file: 
        src="ez_setup.py"
        dest="{{ temp_dir }}"
    - file: 
        src="get-pip.py"
        dest="{{ temp_dir }}"
    - shell: "python2.7 {{ temp_dir }}/ez_setup.py"
    - shell: "python2.7 {{ temp_dir }}/get-pip.py"
